### ISSUE TITLE
Need help registering new map

### ISSUE THREAD

**Issue by amerfathullah** [CiscoDevNet/Glance#2]
Hi Cisco developers, I'm trying to register new map in Cisco Glance using the administrative page. I use the map and masks located inside public/map folder, but after registering them, nothing happens in the home page, even after refreshing.

Detailed documentation on how to use Glance would be helpful.

Thanks in advance.

Regards,
Amer

**Comment by kennych** [comment]
hi @amerfathullah, 
Just go to CMX Setup page -> Floors-> selects the specified floor page -> update the Map to your new uploaded map name.
The map will take effect.

Kenny

**Comment by amerfathullah** [comment]
when I change the map name, I get this error

`{"status":"failure","message":"You are not authorized for this action!","version":"1.0.0.0"}`

**Comment by kennych** [comment]
try  open /admin.html page and login with default admin account(default admin account password is provided in readme)

**Comment by amerfathullah** [comment]
I already login with default admin account, the error still persists

**Comment by amerfathullah** [comment]
the problem only occurs if I change 'normal-glance' in Map field into my map name. If I change anything else, it causes no problem at all.

![Screenshot from 2021-06-18 17-07-20](https://user-images.githubusercontent.com/36897396/122537162-e1906180-d057-11eb-9195-4e3c73f0fec0.png)

**Comment by amerfathullah** [comment]
How to know if I have registered my new map successfully or not?

**Comment by kennych** [comment]
you can try "GET Method of path: /map/normal-glance.svg" to get your uploaded svg format map image.

**Comment by kennych** [comment]
Here has some sample maps : https://github.com/CiscoDevNet/Glance/tree/master/public/map

**Comment by amerfathullah** [comment]
alright, thanks for the help
